const { checkAndCreateLabels } = require("./checkAndCreateLabels");
const { modifyLabelOfSentMessage } = require("./modifyLabelOfSentMessage");

const LABEL = "VACATION_RESPONSE";

/*
    @Description: Sends an autogenerated reply to the specified list of messages and modifies the label of the 'SENT' message.
    @Params:
        gmail: Object - Gmail API client instance (e.g., created using google.gmail({ version: 'v1', auth: oauth2Client }))
        sendList: Array - An array of message objects with properties {id, threadId, From, Subject, To}
    @Return:
        Promise<void> - Resolves when the reply is sent and label modification is successful, rejects with an error message otherwise.
*/
async function sendReply(gmail, sendList) {
    for (let i = 0; i < sendList.length; i++) {
        // prepare message
        let rawMessage = `To: ${sendList[i].From}\r\n`;
        rawMessage += `From: ${sendList[i].To}\r\n`;
        rawMessage += `Subject: Re: ${sendList[i].Subject}\r\n\r\n`;
        rawMessage += 'Autogenerated: I am on vacation. I will get back to you in some days.';

        // Encode message
        const encodedMessage = Buffer.from(rawMessage).toString('base64');

        const sendMessage = {
            raw: encodedMessage,
            'threadId': sendList[i].threadId,
            'In-Reply-To': sendList[i].threadId,
            'References': sendList[i].threadId
        };

        try {
            // send message
            const resp = await gmail.users.messages.send({
                userId: 'me',
                resource: sendMessage
            });
            console.log("Sent Successfully iteration: " + i);

            // modify label of 'SENT' message
            const labelId = await checkAndCreateLabels(gmail, LABEL);
            await modifyLabelOfSentMessage(gmail, resp.data.id, labelId);
        }
        catch (err) {
            console.log(err);
        }
    }
}

module.exports = { sendReply };